### ISSUE TITLE
test_7 failed

### ISSUE THREAD

**Issue by liu-xunnn** [LLNL/pLiner#13]
hello!
When i run the test.sh,test_7 of region-trans failed.
Do you know why?

**Comment by doloresmiao** [comment]
Hello,

Could you give me more information about your testing environment (which option in README.md you are using, for example) and if possible could you paste the error message?

I have tried option 1 (downloading a docker image and run tests within it) but I cannot reproduce the issue you have experienced. I tested this on a computer with AMD Ryzen 7 4800U and 16GB RAM, with Ubuntu LTS 22.04.

I will continue experimenting with other options and get back to you soon.

Best,
Dolores

**Comment by liu-xunnn** [comment]
Thanks for your reply!
Sorry for the incomplete information.
The archetecture is aarch64,and the OS is linux.
pLiner was installed by option 3.
The llvm-9.0.1 was built with clang and clang-tools-extra.

The environment path is:
```
export LD_LIBRARY_PATH=LLVM_DIR/lib
export PATH=LLVM_DIR/bin:$PATH

export PATH=pLiner_DIR/bin:$PATH
```

The test error is like this:
```
region-trans
Error: test_7 and test_7_trans -- comparison failed ( inconsistent result)
- complile&compare failed


20 tests -- 19 pass; 1 failed
```

**Comment by doloresmiao** [comment]
Hello,

I think the issue may be because you are using AArch64, and the architecture used in our benchmarks to reproduce the results are either x64 or Power8. The behavior of compiler-induced inconsistencies may differ across compilers on different architectures.

But just to be sure I will try to reproduce it with a similar environment (an M2 Mac mini). I will get back to you as soon as there is an update. Thank you for your patience!

**Comment by liu-xunnn** [comment]
OK,thank you!

**Comment by doloresmiao** [comment]
Hello, I have tried using option 3 in an AArch64 environment (M2 Mac mini, Docker image https://hub.docker.com/r/arm64v8/ubuntu/) and all tests pass.

I do have an Orange Pi 5 to test in a native AArch64 linux environment but I kinda screwed up the OS on it. It might need some time to set up again. May update you at a later date.

**Comment by liu-xunnn** [comment]
Thank you, I'll also install pLiner again.

**Comment by liu-xunnn** [comment]
Hello,I install the docker and the result is same with yours. I change the gcc11.4 to gcc7.5,but the fail still exists. Finally,the fail of test_7 may be caused by different versioin of ubuntu.Mine is ubuntu22 and yours is ubuntu18.

**Comment by gorgeousboy** [comment]
hello,when the pLiner was installed by option 3. i meet the same failed,my platform information is
The archetecture is x86_64,and the OS is Ubuntu 24.04.1 LTS
The llvm-9.0.1 was built with clang and clang-tools-extra.
gcc version 13.3.0
